### ISSUE TITLE
100% cpu using.

### ISSUE THREAD

**Issue by ghost** [Velesey/SuperMarioBoy#5]
Это многовато. С чем может быть проблема ?

**Comment by Velesey** [comment]
Попробуйте запустить 2.7 версии Python

**Comment by Pydwel** [comment]
Забыл упомянуть,что эта нагрузка наблюдается на Linux,в то время как на Windows используется всего 12% CPU.

**Comment by Pydwel** [comment]
Этот баг открыт на текущее время под номером [https://github.com/pygame/pygame/issues/331](url). К сожалению пишут,что ребилд из источников _не помогает_ и ответа ещё нет.
