### ISSUE TITLE
как файлы в ветку забросить

### ISSUE THREAD

**Issue by dsgbljhs** [Velesey/SuperMarioBoy#6]

**Comment by dsgbljhs** [comment]
код скачен ,но чтобы работал нужна ведь ветка?А я никак их не могу в ветку помести ,всегда создавала ветку а потом тум файлы создавала

**Comment by Velesey** [comment]
я не понимаю о чем речь. Какая ветка? Что туда хотите поместить?

**Comment by dsgbljhs** [comment]
Внимание! Используем python ветки 2.х, с 3.х

**Comment by dsgbljhs** [comment]
![79](https://user-images.githubusercontent.com/45237319/52530782-8ded0b00-2d1b-11e9-8f94-45f06f6d9cd8.png)
чтобы красным не подчеркивалось и другие файлы могли переместиться в этот надо их в ветку поместить

**Comment by Denya56** [comment]
о чем вы?

**Comment by Velesey** [comment]
Вам нужно настроить PyCharm https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
